### PR TITLE
networkmanager: use systemd-resolved as default dns resolver

### PR DESCRIPTION
**Pull request by vnepogodin**
implements config changes required for https://github.com/CachyOS/CachyOS-Settings/issues/79

### CODE REVIEW

**Comment by 1Naim** [comment]
What if a user is already using a different dns resolver, e.g. aformentioned dnsproxy in #79 or cloudflare-warp?

**Comment by vnepogodin** [comment]
> What if a user is already using a different dns resolver, e.g. aformentioned dnsproxy in #79 or cloudflare-warp?

If the user already configured networkmanager to use dnsproxy in /etc, then our config will be overwritten. dnsproxy will be still used instead of systemd-resolved

**Review by 1Naim — APPROVED** [review]
Seems to work with cloudflare-warp. It adds these two extra lines in `/etc/resolv.conf` on top of what cloudflare-warp sets

```bash
# /etc/resolv.conf

# This file was generated by cloudflare-warp.
nameserver 127.0.2.2
nameserver 127.0.2.3
options edns0
options trust-ad

**Review by ptr1337 — APPROVED** [review]

**Comment by iamshadow2008** [comment]
Systemd-resolved breaks my personal setup. I have my own caching DNS server set up on my network, using dnscrypt-proxy and NextDNS. After installing the cachyos-settings update that includes this change, my two systems can no longer resolve any hosts. Disabling systemd-resolved and removing the usr/lib/NetworkManager/conf.d/dns.conf file and rebooting, systems work fine again. Will I have to do that every time the package updates?

Even if it did "work" I would prefer to not have multiple large independent caches as that could cause problems.

**Comment by vnepogodin** [comment]
> Systemd-resolved breaks my personal setup. I have my own caching DNS server set up on my network, using dnscrypt-proxy and NextDNS (separate device hosting this and other services). After installing the cachyos-settings update that includes this change, my two systems can no longer resolve any hosts. Disabling systemd-resolved and removing the usr/lib/NetworkManager/conf.d/dns.conf file and rebooting, systems work fine again. Will I have to do that every time the package updates?
> 
> Even if it did "work" I would prefer to not have multiple large independent caches as that could cause problems.

well if you had already setup the networkmanager to use custom dns, e.g dnscrypt-proxy or dnsmasq then the settings update shouldnt cause any changes on your side.

if you put (for example) to `/etc/NetworkManager/conf.d/dns.conf` then resolved wont be used as our settings gets overwritten with config in /etc

https://wiki.archlinux.org/title/NetworkManager#dnsmasq
https://wiki.archlinux.org/title/NetworkManager#Unmanaged_/etc/resolv.conf

**Comment by iamshadow2008** [comment]
No client side configuration was done, as my dns server is network-wide. When connecting to the network the dns server information is sent to the client thru dhcp.

**Comment by TheWyn** [comment]
> if you had already setup the networkmanager to use custom dns, e.g dnscrypt-proxy or dnsmasq then the settings update shouldnt cause any changes on your side.

With systemd-resolved now enabled by default should dnsmasq not be installed by default in calamares?

**Pull request merged**
