### PR TITLE
Enable defer+madvise defragmention for THP by default

### PR DESCRIPTION
**Pull request by ventureoo**
This should improve the performance of applications that use the tcmalloc memory allocator, which is used by Chromium/Electron and Valve's native games, among others.
Ref: https://github.com/google/tcmalloc/blob/master/docs/tuning.md#system-level-optimizations

### CODE REVIEW

**Comment by Boria138** [comment]
I guess the settings could be a little more customized

w- /sys/kernel/mm/transparent_hugepage/enabled - - - - - madvise
w- /sys/kernel/mm/transparent_hugepage/khugepaged/defrag - - - - - - 1
w- /sys/kernel/mm/transparent_hugepage/defrag - - - - - defer+madvise

**Comment by Boria138** [comment]
@ventureoo 
```Failed to write file "/sys/kernel/mm/transparent_hugepage/defrag": Invalid argument```

**Comment by Torston420** [comment]
[Kernel docs](https://www.kernel.org/doc/html/next/admin-guide/mm/transhuge.html#global-thp-controls) imply that 'madvise' would perform the stalling behavior seen in 'always', wouldn't 'defer' be more advantageous than 'defer+madvise' for interactivity?

**Comment by ventureoo** [comment]
> Update: Team Fortress 2 does not seem to allocate any hugepages at all if /transparent_hugepage/enabled is set to 'madvise' instead of 'always', this appears to be a global issue with TCMalloc: https://github.com/google/tcmalloc/issues/85

Thanks for notice. I'll remove madvise for `transparent_hugepage/enabled` in that case.

**Comment by ventureoo** [comment]
@ptr1337 I've signed the last commit. Are there any objections to this PR?

**Pull request merged**
